repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.6.0"
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: detect-private-key
        exclude: ^traefik\/localhost\/key.pem$
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.89.1"
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
